services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webtruyen_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webtruyen_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    image: node:18-alpine
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/uploads
      - ./logs/backend:/app/logs
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/webtruyen_dev
      JWT_SECRET: dev-jwt-secret-key-not-for-production
      JWT_REFRESH_SECRET: dev-refresh-secret-key-not-for-production
      FRONTEND_URL: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    command: sh -c "npm install && npx prisma generate && npm run dev"
    networks:
      - app-network

  frontend:
    image: node:18-alpine
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_PUBLIC_FRONTEND_URL: http://localhost:3000
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"  # Different port for development
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uploads:/uploads:ro
      - ./logs/nginx:/var/log/nginx
    environment:
      - DOMAIN=localhost
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgres_data_dev:

networks:
  app-network:
    driver: bridge
