services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  webtruyen_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env.prod
    volumes:
      - ./uploads:/uploads
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network

  webtruyen_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env.prod
    ports:
      - "3000:3000"
    depends_on:
      - webtruyen_backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/.next:/usr/share/nginx/html:ro
      - ./uploads:/uploads
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - webtruyen_frontend
      - webtruyen_backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
